# Generated by Django 4.1 on 2023-06-08 11:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appro', models.DateField(blank=True, default=datetime.date.today, verbose_name='date')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Civilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consommation', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('date_du', models.DateField(default=datetime.date.today, verbose_name='date du')),
                ('date_au', models.DateField(default=datetime.date.today, verbose_name='date au')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
            ],
            options={
                'ordering': ('-date_consommation',),
            },
        ),
        migrations.CreateModel(
            name='Constructeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('etat_contrat', models.CharField(choices=[('En cours', 'En cours'), ('Suspendu', 'Suspendu'), ('Résilié', 'Résilié')], default='En cours', max_length=10, verbose_name='etat du contrat')),
                ('date_contrat', models.DateField(blank=True, default=datetime.date.today, verbose_name='date du contrat')),
                ('observation', models.TextField(blank=True, default='', verbose_name='observation')),
            ],
            options={
                'ordering': ('-date_contrat',),
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date')),
                ('modePaiement', models.CharField(choices=[('E', 'Espèces'), ('C', 'Chèque'), ('V', 'Virement')], default='E', max_length=1, verbose_name='mode')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='dépôt')),
                ('sigle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='sigle')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('contact', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='contact')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Detailsinventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, default=0, verbose_name='quantité')),
            ],
        ),
        migrations.CreateModel(
            name='Emballage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_emballage', models.CharField(blank=True, choices=[('Aucun', 'Aucun'), ('Carton', 'Carton'), ('Paquet', 'Paquet'), ('Gobelet', 'Gobelet'), ('Boite', 'Boite'), ('Sachet', 'Sachet')], max_length=20, verbose_name='type emballage')),
                ('libelle', models.CharField(blank=True, max_length=50, unique=True, verbose_name='libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(choices=[('Exercice 2023', 'Exercice 2023'), ('Exercice 2022', 'Exercice 2022'), ('Exercice 2021', 'Exercice 2021'), ('Exercice 2020', 'Exercice 2020')], default='Exercice 2023', max_length=15, unique=True, verbose_name='exercice')),
                ('date_debut', models.DateField(blank=True, default=datetime.date.today, verbose_name='date début')),
                ('date_fin', models.DateField(blank=True, default=datetime.date.today, verbose_name='date fin')),
                ('date_cloture', models.DateField(blank=True, default=datetime.date.today, verbose_name='date clôture')),
                ('etat', models.BooleanField(blank=True, default=False, verbose_name='clôturé')),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_installation', models.DateField(blank=True, default=datetime.date.today, verbose_name='date installation')),
                ('etat', models.BooleanField(blank=True, default=True, verbose_name='en service')),
                ('observation', models.CharField(blank=True, default='', max_length=100, verbose_name='observation')),
                ('mode', models.SmallIntegerField(default=0, verbose_name='type de contrat')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.contrat')),
            ],
            options={
                'ordering': ('date_installation',),
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=255, unique=True, verbose_name='matricule')),
                ('libelle', models.CharField(max_length=50, verbose_name='libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=50, verbose_name='abrégé')),
                ('numero_serie', models.CharField(blank=True, default='', max_length=30, verbose_name='numéro de série')),
                ('etat', models.CharField(blank=True, choices=[('En service', 'En service'), ('Disponible', 'Disponible'), ('Hors service', 'Hors service')], default='En service', max_length=15, verbose_name='état')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='machines', verbose_name='photo')),
                ('constructeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametre.constructeur', verbose_name='constructeur')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.continent', verbose_name='Continent')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='site ou client')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='abrégé')),
            ],
        ),
        migrations.CreateModel(
            name='TypeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='abrégé')),
            ],
            options={
                'ordering': ('libelle',),
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.departement', verbose_name='Département')),
            ],
        ),
        migrations.CreateModel(
            name='Tasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='Observation')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.composition')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raisonSociale', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('sigle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sigle')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Cellulaire')),
                ('photo', models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='Photo')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='Logo')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.ville', verbose_name='ville')),
            ],
        ),
        migrations.CreateModel(
            name='Releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_releve', models.DateField(default=datetime.date.today, verbose_name='date relevé')),
                ('periode', models.CharField(blank=True, default='Juin 2023', max_length=225, verbose_name='période')),
                ('date_debut', models.DateField(blank=True, default=datetime.date.today, verbose_name='date début')),
                ('date_fin', models.DateField(blank=True, default=datetime.date.today, verbose_name='date fin')),
                ('index_anterieur', models.SmallIntegerField(blank=True, default=0, verbose_name='index antérieur')),
                ('index_nouveau', models.SmallIntegerField(blank=True, default=100, verbose_name='index nouveau')),
                ('test', models.SmallIntegerField(blank=True, default=0, verbose_name='test')),
                ('remboursement', models.SmallIntegerField(blank=True, default=0, verbose_name='remboursement')),
                ('facture', models.BooleanField(blank=True, default=False, verbose_name='Facturé')),
                ('solde', models.BooleanField(blank=True, default=False, verbose_name='soldé')),
                ('observation', models.CharField(blank=True, default='', max_length=255, verbose_name='observation')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.installation', verbose_name='machine installée')),
            ],
            options={
                'ordering': ['-date_releve'],
                'unique_together': {('installation', 'date_releve')},
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.pays', verbose_name='Pays')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('email', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='e-mail')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='sexe')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='photo')),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.civilite', verbose_name='civilité')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.fonction', verbose_name='fonction')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.profession', verbose_name='profession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="nom d'utilisateur")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitemesure', models.CharField(blank=True, choices=[('Kg', 'Kg'), ('L', 'L'), ('M2', 'M2')], default='Kg', max_length=15, verbose_name='unité de mesure')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='produit')),
                ('prix', models.IntegerField(blank=True, default=0, verbose_name='prix')),
                ('stocke', models.BooleanField(blank=True, default=True, verbose_name='stocké')),
                ('type_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.typeproduit', verbose_name='type produit')),
            ],
            options={
                'ordering': ['libelle'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField(default=datetime.date.today, verbose_name='date inventaire')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.depot', verbose_name='dépôt')),
                ('produits', models.ManyToManyField(through='parametre.Detailsinventaire', to='parametre.produit', verbose_name='produits inventoriés')),
            ],
        ),
        migrations.AddField(
            model_name='installation',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.machine'),
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('prenoms', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='prénoms')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='e-mail')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='adresse')),
                ('fax', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='fax')),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.civilite', verbose_name='civilité')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Facturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facturation_numero', models.CharField(blank=True, default='', max_length=30, verbose_name='numéro facture')),
                ('date_facturation', models.DateField(blank=True, default=datetime.date.today, verbose_name='date facture')),
                ('montant', models.SmallIntegerField(default=0, verbose_name='montant')),
                ('observation', models.CharField(blank=True, default='', max_length=255, verbose_name='observation')),
                ('releves', models.ManyToManyField(to='parametre.releve')),
            ],
            options={
                'ordering': ['-date_facturation'],
            },
        ),
        migrations.CreateModel(
            name='Encaisser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_encaisser', models.DateField(default=datetime.date.today, verbose_name='date en caisser')),
                ('montant', models.IntegerField(blank=True, default=0, verbose_name='montant')),
                ('type_encaisser', models.BooleanField(blank=True, default=True, verbose_name="type d'encaissement")),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.installation', verbose_name='installation')),
            ],
        ),
        migrations.AddField(
            model_name='detailsinventaire',
            name='inventaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.inventaire', verbose_name='inventaire'),
        ),
        migrations.AddField(
            model_name='detailsinventaire',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.produit', verbose_name='produit'),
        ),
        migrations.CreateModel(
            name='DetailsDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, default='', max_length=255, verbose_name='objet')),
                ('quantite', models.SmallIntegerField(blank=True, default=1, verbose_name='quantite')),
                ('pu', models.SmallIntegerField(blank=True, default=1000, verbose_name='pu')),
                ('mode_paiement', models.CharField(choices=[('E', 'Espèces'), ('C', 'Chèque'), ('V', 'Virement')], default='C', max_length=1, verbose_name='mode')),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.depense')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Detailsconsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.SmallIntegerField(blank=True, default=1, verbose_name='quantité')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
                ('consommation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.consommation')),
                ('tasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.tasse')),
            ],
        ),
        migrations.CreateModel(
            name='Detailscommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.SmallIntegerField(blank=True, default=1, verbose_name='quantié')),
                ('pu', models.SmallIntegerField(blank=True, default=0, verbose_name='prix unitaire')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.produit')),
            ],
            options={
                'unique_together': {('commande', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='Detailsappro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.SmallIntegerField(blank=True, default=1, verbose_name='quantié')),
                ('pu', models.SmallIntegerField(blank=True, default=0, verbose_name='prix unitaire')),
                ('appro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.appro')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.produit')),
            ],
            options={
                'unique_together': {('appro', 'produit')},
            },
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.region', verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='machines',
            field=models.ManyToManyField(through='parametre.Installation', to='parametre.machine', verbose_name='machines installées'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.site', verbose_name='site'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='nom')),
                ('prenoms', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='prénoms')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone')),
                ('cellulaire', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire')),
                ('fax', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='fax')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='e-mail')),
                ('adresse', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='adresse')),
                ('civilite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.civilite', verbose_name='civilité')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.contrat', verbose_name='fonction')),
                ('fonction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametre.fonction', verbose_name='fonction')),
                ('profession', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametre.profession')),
            ],
            options={
                'ordering': ('nom',),
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Abrégé')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.ville', verbose_name='Ville')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.installation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(through='parametre.Detailscommande', to='parametre.produit', verbose_name='produits commandés'),
        ),
        migrations.AddField(
            model_name='appro',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.fournisseur'),
        ),
        migrations.AddField(
            model_name='appro',
            name='produits',
            field=models.ManyToManyField(through='parametre.Detailsappro', to='parametre.produit', verbose_name='produits'),
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé')),
                ('abrege', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Abrégé')),
                ('typeActivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.typeactivite', verbose_name="Type d'activite")),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(blank=True, choices=[('Vente libre', 'Vente libre'), ('Forfait', 'Forfait'), ('Palier', 'Palier')], max_length=20, verbose_name='type')),
                ('date_tarification', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='date tarification')),
                ('quantite', models.SmallIntegerField(blank=True, default=1000, verbose_name='quantié')),
                ('pu', models.SmallIntegerField(blank=True, default=200, verbose_name='prix unitaire')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.installation')),
            ],
            options={
                'unique_together': {('installation', 'type_contrat', 'date_tarification')},
            },
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reglement', models.DateField(default=datetime.date.today, verbose_name='date règlement')),
                ('montant', models.SmallIntegerField(default=0, verbose_name='montant')),
                ('observation', models.CharField(blank=True, default='', max_length=255, verbose_name='observation')),
                ('facturation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.facturation', verbose_name='facture')),
            ],
            options={
                'unique_together': {('facturation', 'date_reglement')},
            },
        ),
        migrations.CreateModel(
            name='ProduitEmballage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_unitaire', models.FloatField(blank=True, default=1, verbose_name='quantité unitaire')),
                ('valeur_unitaire', models.FloatField(blank=True, default=1, verbose_name='valeur unitaire')),
                ('libelle_quantite_unitaire', models.CharField(blank=True, default='', max_length=50, verbose_name='lqu')),
                ('libelle_valeur_unitaire', models.CharField(blank=True, default='', max_length=50, verbose_name='lvu')),
                ('emballage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.emballage', verbose_name='emballage')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.produit', verbose_name='produit')),
            ],
            options={
                'ordering': ['produit'],
                'unique_together': {('produit', 'emballage')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=datetime.date.today, verbose_name='date paiement')),
                ('montant', models.SmallIntegerField(default=0, verbose_name='montant')),
                ('observation', models.CharField(blank=True, default='', max_length=255, verbose_name='observation')),
                ('appro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.appro', verbose_name='approvisionnement')),
            ],
            options={
                'unique_together': {('appro', 'date_paiement')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='detailsinventaire',
            unique_together={('inventaire', 'produit')},
        ),
        migrations.CreateModel(
            name='Detailscomposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.SmallIntegerField(blank=True, default=1, verbose_name='quantité')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.composition')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.produit')),
            ],
            options={
                'unique_together': {('composition', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='Cloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cloture', models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3'), ('Trimestre 4', 'Trimestre 4')], default='Trimestre 1', max_length=15, verbose_name='type de clôture')),
                ('date_cloture', models.DateField(blank=True, default=datetime.date.today, verbose_name='date clôture')),
                ('etat', models.BooleanField(blank=True, default=False, verbose_name='clôturé')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.exercice', verbose_name='exercice comptable')),
            ],
            options={
                'ordering': ('-exercice__annee', '-type_cloture'),
                'unique_together': {('exercice', 'type_cloture')},
            },
        ),
    ]
