# Generated by Django 4.1 on 2023-06-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='type_contrat',
            field=models.CharField(choices=[('Vente libre', 'Vente libre'), ('Forfait', 'Forfait'), ('Palier', 'Palier')], default='Vente libre', max_length=20, verbose_name='type de contrat'),
        ),
        migrations.AlterUniqueTogether(
            name='installation',
            unique_together={('contrat', 'machine', 'date_installation')},
        ),
        migrations.RemoveField(
            model_name='installation',
            name='mode',
        ),
    ]
