# Generated by Django 4.1 on 2023-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0004_alter_facturation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='periode',
            field=models.CharField(blank=True, default='Juin 2023', max_length=225, verbose_name='période'),
        ),
    ]
