# Generated by Django 4.1 on 2023-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0005_facturation_periode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='periode',
            field=models.CharField(blank=True, default='Mai 2023', max_length=225, verbose_name='période'),
        ),
    ]
