# Generated by Django 4.1 on 2023-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0006_alter_facturation_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='référence'),
        ),
    ]
