# Generated by Django 4.1 on 2023-06-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0007_facturation_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='reference',
            field=models.CharField(max_length=255, verbose_name='référence'),
        ),
    ]
