# Generated by Django 4.1 on 2023-06-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0009_rename_facturation_numero_facturation_periode_du_au'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='periode_du_au',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='période du au'),
        ),
    ]
