# Generated by Django 4.1 on 2023-06-10 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0012_alter_facturation_periode_du_au'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='facturation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date facture'),
        ),
    ]
