# Generated by Django 4.1 on 2023-06-10 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0014_alter_facturation_facturation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='facturation_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 10), verbose_name='date facture'),
        ),
    ]
