# Generated by Django 4.1 on 2023-06-10 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0016_alter_facturation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturation',
            name='facturation_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='date facture'),
        ),
    ]
