# Generated by Django 4.1 on 2023-06-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0017_facturation_facturation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturation',
            options={'ordering': ['-facturation_date']},
        ),
    ]
