# Generated by Django 4.1 on 2023-06-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0022_alter_facturation_facturation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturation',
            name='periode_du_au',
            field=models.CharField(blank=True, default='DU 01/5/2023 AU 2023-05-31', max_length=50, verbose_name='période du au'),
        ),
    ]
