# Generated by Django 4.1 on 2023-06-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0026_rename_abrege_site_sigle_site_cellulaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='emplacement',
            field=models.CharField(default='', max_length=100, verbose_name='emplacement'),
        ),
    ]
