# Generated by Django 4.1 on 2023-06-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0027_site_emplacement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['libelle']},
        ),
    ]
