# Generated by Django 4.1 on 2023-06-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0028_alter_site_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='cellulaire',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='raisonSociale',
            field=models.CharField(max_length=255, unique=True, verbose_name='raison sociale'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='sigle',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='sigle'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone'),
        ),
    ]
