# Generated by Django 4.1 on 2023-06-18 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0029_alter_societe_cellulaire_alter_societe_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opération', models.DateField(default=datetime.date.today, verbose_name='date opération')),
                ('montant', models.IntegerField(blank=True, default=0, verbose_name='montant')),
                ('type_operation', models.BooleanField(blank=True, default=True, verbose_name='type opération')),
                ('observation', models.CharField(blank=True, default='', max_length=225, verbose_name='observation')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametre.installation', verbose_name='installation')),
            ],
        ),
        migrations.DeleteModel(
            name='Encaisser',
        ),
    ]
