# Generated by Django 4.1 on 2023-06-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0030_caisse_delete_encaisser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caisse',
            old_name='date_opération',
            new_name='date_operation',
        ),
    ]
