# Generated by Django 4.1 on 2023-06-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0033_alter_caisse_type_operation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': [('-date_operation',)]},
        ),
        migrations.AlterUniqueTogether(
            name='caisse',
            unique_together={('installation', 'date_operation', 'type_operation')},
        ),
    ]
