# Generated by Django 4.1 on 2023-06-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0034_alter_caisse_options_alter_caisse_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': ['-date_operation']},
        ),
    ]
