# Generated by Django 4.1 on 2023-06-21 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0035_alter_caisse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventaire',
            options={'ordering': ['-date_inventaire']},
        ),
        migrations.AlterUniqueTogether(
            name='inventaire',
            unique_together={('depot', 'date_inventaire')},
        ),
    ]
