# Generated by Django 4.1 on 2023-06-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0036_alter_inventaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='cellulaire1',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='cellulaire'),
        ),
        migrations.AddField(
            model_name='societe',
            name='fichier_page_accueil',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='fichier page accueil'),
        ),
        migrations.AddField(
            model_name='societe',
            name='html_societe_court',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='nom société court html'),
        ),
        migrations.AddField(
            model_name='societe',
            name='html_societe_long',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='nom société long html'),
        ),
        migrations.AddField(
            model_name='societe',
            name='html_titre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='titre onglet navigateur'),
        ),
        migrations.AddField(
            model_name='societe',
            name='telephone1',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='téléphone'),
        ),
    ]
